<?php

declare(strict_types=1);

namespace Parisek\Styleguide;

/**
 * @internal Server-side icon catalog backing the `#icons` foundations
 * section (#87).
 *
 * Reads the yaml `icons:` block (groups of `ico-*.svg` entries generated by
 * the consumer's sync tooling — see portadesign/tailwind-base#272) and
 * returns inline-ready SVG markup per icon. Icons must be inlined — not
 * referenced via `<img>` — because the whole icon contract is built on
 * `fill="currentColor"` inheriting the parent's text color, and `<img>`
 * isolates the SVG from CSS inheritance.
 *
 * Consumer icon files are Twig fragments, not plain SVG: the project's
 * `icons.get()` macro renders them with an `{{ attribute }}` placeholder on
 * the root element. Inlining the raw file would print that literal, so the
 * placeholder is stripped here. Legacy icons that predate the project-side
 * correctness contract may also carry fixed `width`/`height` root attributes
 * (sometimes without a `viewBox`); the catalog normalizes both so every tile
 * scales uniformly: a missing `viewBox` is synthesized from the fixed
 * dimensions, then the dimensions are dropped.
 *
 * Sanitization is defense-in-depth (the files come from the consuming
 * project's own repository — same trust level as its templates), but it's
 * implemented as a real trust boundary anyway because the markup is echoed
 * `|raw` into the page: the file is parsed as XML (network access off, DTDs
 * rejected), executable vectors are removed from the DOM, URL attributes
 * are reduced to fragment references, and only the re-serialized tree is
 * emitted. An entry that doesn't parse as an `<svg>` root renders as a
 * missing-state tile rather than being echoed.
 *
 * Every filesystem read is routed through {@see PathGuard::resolvePath()} —
 * same containment/scheme-rejection hardening as {@see FaviconAudit} /
 * {@see OgImageAudit}.
 *
 * Pure, static, no I/O beyond reading the icon files it's told about.
 *
 * @phpstan-type IconItem array{name: string, label: string|null, file: string, color: string, exists: bool, svg: string|null}
 * @phpstan-type IconGroup array{key: string, label: string, items: list<IconItem>}
 * @phpstan-type IconsResult array{groups: list<IconGroup>, total: int}
 */
final class IconsCatalog
{
    private const COLOR_MONO = 'mono';

    private const COLOR_MULTI = 'multi';

    private const MAX_FILE_BYTES = 512_000;

    /**
     * Builds the normalized catalog, or null when the yaml block is absent
     * or carries no renderable group — the template gates the whole section
     * on the result, so older projects without an `icons:` block simply
     * don't get the section (never an error).
     *
     * @return IconsResult|null
     */
    public static function build(string $staticPath, mixed $icons): ?array
    {
        if (!is_array($icons) || !is_array($icons['groups'] ?? null)) {
            return null;
        }

        $groups = [];
        $total = 0;
        foreach ($icons['groups'] as $group) {
            if (!is_array($group)) {
                continue;
            }
            $items = [];
            foreach (is_array($group['items'] ?? null) ? $group['items'] : [] as $item) {
                $built = self::buildItem($staticPath, $item);
                if ($built !== null) {
                    $items[] = $built;
                }
            }
            if ($items === []) {
                continue;
            }
            $key = self::stringOrNull($group['key'] ?? null) ?? 'icons';
            $groups[] = [
                'key' => $key,
                'label' => self::stringOrNull($group['label'] ?? null) ?? $key,
                'items' => $items,
            ];
            $total += count($items);
        }

        if ($groups === []) {
            return null;
        }

        return ['groups' => $groups, 'total' => $total];
    }

    /**
     * @return IconItem|null null when the entry has no usable `name` — a
     *                       nameless entry can't be labeled or referenced
     *                       via `icons.get()`, so it's dropped rather than
     *                       rendered as an anonymous tile
     */
    private static function buildItem(string $staticPath, mixed $item): ?array
    {
        if (!is_array($item)) {
            return null;
        }
        $name = self::stringOrNull($item['name'] ?? null);
        if ($name === null) {
            return null;
        }

        $label = self::stringOrNull($item['label'] ?? null);
        $file = self::stringOrNull($item['file'] ?? null) ?? '';
        $configuredColor = self::stringOrNull($item['color'] ?? null);
        $color = in_array($configuredColor, [self::COLOR_MONO, self::COLOR_MULTI], true)
            ? $configuredColor
            : null;

        $svg = self::inlineSvg($staticPath, $file);
        if ($svg === null) {
            return [
                'name' => $name,
                'label' => $label,
                'file' => $file,
                'color' => $color ?? self::COLOR_MONO,
                'exists' => false,
                'svg' => null,
            ];
        }

        return [
            'name' => $name,
            'label' => $label,
            'file' => $file,
            // The sync tooling writes `color:` from its own SVG parse; when
            // the yaml omits it (hand-authored block), fall back to the same
            // signal it uses — currentColor present means the icon rides the
            // inheritance channel, anything else carries its own fills.
            'color' => $color ?? (stripos($svg, 'currentColor') !== false ? self::COLOR_MONO : self::COLOR_MULTI),
            'exists' => true,
            'svg' => $svg,
        ];
    }

    /**
     * Reads, normalizes and sanitizes one icon file into inline-ready
     * markup. Returns null for anything that can't be safely inlined —
     * external/scheme URLs, paths escaping the static root, unreadable
     * files, or content without an `<svg>` root — the caller renders those
     * as a missing-state tile.
     */
    private static function inlineSvg(string $staticPath, string $file): ?string
    {
        if ($file === '' || PathGuard::isExternalUrl($file) || PathGuard::pathEscapesRoot($staticPath, $file)) {
            return null;
        }

        $absolute = PathGuard::resolvePath(rtrim($staticPath, '/'), $file);
        if ($absolute === null) {
            return null;
        }

        // Icon files are a few KB; anything bigger is either not an icon or
        // a resource-exhaustion attempt — cap before reading/parsing.
        $size = filesize($absolute);
        if ($size === false || $size > self::MAX_FILE_BYTES) {
            return null;
        }

        $content = file_get_contents($absolute);
        if ($content === false) {
            return null;
        }

        return self::sanitizeAndNormalize(self::stripTwigAttributePlaceholder($content));
    }

    /**
     * Consumer icon files carry the project-side `{{ attribute }}` Twig
     * placeholder on the root element (rendered by the `icons.get()` macro).
     * This catalog inlines the file outside any Twig render of it, so the
     * placeholder — with any spacing variant — is dropped.
     */
    private static function stripTwigAttributePlaceholder(string $content): string
    {
        return (string) preg_replace('/\{\{\s*attribute\s*\}\}/', '', $content);
    }

    /**
     * DOM-based sanitize + normalize round-trip. A real XML parse is the
     * trust boundary here (not regexes — unquoted attributes, mixed casing
     * and entity-encoded schemes all bypass pattern matching but can't
     * bypass the parser): the document is parsed with network access
     * disabled, DTDs are rejected outright (no entity tricks), executable
     * elements and event-handler attributes are removed from the tree, URL
     * attributes are reduced to same-document fragment references, and the
     * root element is normalized for uniform grid tiles — legacy icons
     * predating the project-side correctness contract carry fixed
     * `width`/`height` attributes that would override the tile's sizing
     * classes, so a missing `viewBox` is synthesized from them before
     * they're dropped. Serialization re-emits only what the parser
     * understood; the reformatting a DOM round-trip implies is the point,
     * not a cost.
     *
     * Returns null for anything that doesn't parse as a lone `<svg>`
     * document — actual HTML, plain text, or DTD-carrying files.
     */
    private static function sanitizeAndNormalize(string $content): ?string
    {
        $previous = libxml_use_internal_errors(true);
        try {
            $dom = new \DOMDocument();
            $loaded = $dom->loadXML($content, LIBXML_NONET);
        } finally {
            libxml_clear_errors();
            libxml_use_internal_errors($previous);
        }
        if ($loaded !== true || $dom->doctype !== null) {
            return null;
        }

        $root = $dom->documentElement;
        if ($root === null || strtolower($root->localName ?? '') !== 'svg') {
            return null;
        }

        self::sanitizeNode($root);
        self::normalizeRoot($root);

        $xml = $dom->saveXML($root);

        return $xml === false ? null : trim($xml);
    }

    /**
     * Depth-first removal of executable/exfiltration vectors:
     * `<script>`/`<foreignObject>`/`<style>` elements, comments and
     * processing instructions, `on*` event-handler attributes (any
     * casing/quoting — the parser already normalized both), `style`
     * attributes (CSS can carry external `url(…)` fetches; the project-side
     * icon contract bans embedded styling anyway — presentation attributes
     * are the sanctioned channel), and URL-bearing attributes
     * (`href`/`xlink:href`/`src`) whose value isn't a same-document fragment
     * reference (`#…`) — entity decoding has already happened at parse time,
     * so an encoded `javascript:` can't masquerade past the check.
     */
    private static function sanitizeNode(\DOMElement $element): void
    {
        foreach (iterator_to_array($element->childNodes) as $child) {
            if ($child instanceof \DOMElement) {
                if (in_array(strtolower($child->localName ?? ''), ['script', 'foreignobject', 'style'], true)) {
                    $element->removeChild($child);
                    continue;
                }
                self::sanitizeNode($child);
            } elseif ($child instanceof \DOMComment || $child instanceof \DOMProcessingInstruction) {
                $element->removeChild($child);
            }
        }

        foreach (iterator_to_array($element->attributes ?? []) as $attribute) {
            if (!$attribute instanceof \DOMAttr) {
                continue;
            }
            $name = strtolower($attribute->localName ?? $attribute->name);
            if (str_starts_with($name, 'on') || $name === 'style') {
                $element->removeAttributeNode($attribute);
                continue;
            }
            if (in_array($name, ['href', 'src'], true)) {
                // Browsers trim/collapse control characters and whitespace
                // before resolving a URL — mirror that before the check.
                $value = (string) preg_replace('/[\x00-\x20]+/', '', $attribute->value);
                if (!str_starts_with($value, '#')) {
                    $element->removeAttributeNode($attribute);
                }
            }
        }
    }

    /**
     * Root normalization for uniform tiles (see sanitizeAndNormalize):
     * synthesize `viewBox` from fixed dimensions when absent, then drop the
     * dimensions so the tile's sizing classes win.
     */
    private static function normalizeRoot(\DOMElement $root): void
    {
        $width = self::floatAttribute($root->getAttribute('width'));
        $height = self::floatAttribute($root->getAttribute('height'));

        if (!$root->hasAttribute('viewBox') && $width !== null && $width > 0 && $height !== null && $height > 0) {
            $root->setAttribute('viewBox', sprintf('0 0 %s %s', self::formatDimension($width), self::formatDimension($height)));
        }
        $root->removeAttribute('width');
        $root->removeAttribute('height');
    }

    /**
     * Accepts only a plain (optionally px-suffixed) numeric value — `100%`,
     * `2em` and friends are rejected outright rather than truncated to a
     * bogus number.
     */
    private static function floatAttribute(string $value): ?float
    {
        if (preg_match('/^\s*([0-9]*\.?[0-9]+)(px)?\s*$/i', $value, $m) !== 1) {
            return null;
        }

        return (float) $m[1];
    }

    private static function formatDimension(float $value): string
    {
        return rtrim(rtrim(sprintf('%.4F', $value), '0'), '.');
    }

    private static function stringOrNull(mixed $value): ?string
    {
        if (!is_string($value) || trim($value) === '') {
            return null;
        }

        return trim($value);
    }
}
